### ISSUE TITLE
Catching exceptions from contract calls.

### ISSUE THREAD

**Issue by AntonAndell** [icon-project/javaee-unittest#16]
See comment in code
```
    Object call(Account from, boolean readonly, BigInteger value, String method, Object... params) {
        sm.pushFrame(from, this.score, readonly, method, value);
        Class<?>[] paramClasses = new Class<?>[params.length];
        for (int i = 0; i < params.length; i++) {
            Class<?> type = params[i].getClass();
            // Convert supported object types to primitive data types
            if (type == Integer.class) {
                paramClasses[i] = Integer.TYPE; // int
            } else if (type == Long.class) {
                paramClasses[i] = Long.TYPE; // long
            } else if (type == Short.class) {
                paramClasses[i] = Short.TYPE; // short
            } else if (type == Character.class) {
                paramClasses[i] = Character.TYPE; // char
            } else if (type == Byte.class) {
                paramClasses[i] = Byte.TYPE; // byte
            } else if (type == Boolean.class) {
                paramClasses[i] = Boolean.TYPE; // boolean
            } else {
                paramClasses[i] = type;
            }
        }
        try {
            Class<?> clazz = instance.getClass();
            var m = clazz.getMethod(method, paramClasses);
            return m.invoke(instance, params);
        } catch (NoSuchMethodException | IllegalAccessException e) {
            e.printStackTrace();
            throw new RuntimeException(e.getMessage());
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            // Here we always throw AssertionErrors but it is not what me might get when running on the network. 
            // The contract can raise any type of runtime expection.
            throw new AssertionError(e.getTargetException().getMessage()); 
        } finally {
            sm.popFrame();
        }
    }
```
    
Suggested change would be something like 
    
```
    Object call(Account from, boolean readonly, BigInteger value, String method, Object... params) {
        sm.pushFrame(from, this.score, readonly, method, value);
        Class<?>[] paramClasses = new Class<?>[params.length];
        for (int i = 0; i < params.length; i++) {
            Class<?> type = params[i].getClass();
            // Convert supported object types to primitive data types
            if (type == Integer.class) {
                paramClasses[i] = Integer.TYPE; // int
            } else if (type == Long.class) {
                paramClasses[i] = Long.TYPE; // long
            } else if (type == Short.class) {
                paramClasses[i] = Short.TYPE; // short
            } else if (type == Character.class) {
                paramClasses[i] = Character.TYPE; // char
            } else if (type == Byte.class) {
                paramClasses[i] = Byte.TYPE; // byte
            } else if (type == Boolean.class) {
                paramClasses[i] = Boolean.TYPE; // boolean
            } else {
                paramClasses[i] = type;
            }
        }
        try {
            Class<?> clazz = instance.getClass();
            var m = clazz.getMethod(method, paramClasses);
            return m.invoke(instance, params);
        } catch (NoSuchMethodException | IllegalAccessException e) {
            e.printStackTrace();
            throw new RuntimeException(e.getMessage());
        } catch (InvocationTargetException e) {
            e.printStackTrace();
             if (RuntimeException.class.isAssignableFrom(e.getCause().getClass())) { 
                //Possibly check stack size and always throw AssertionError if size is 1
                throw (RuntimeException) e.getCause();
            }
            
            throw new AssertionError(e.getTargetException().getMessage()); 
        } finally {
            sm.popFrame();
        }
    }
```

**Comment by sink772** [comment]
It seems you are expecting the same RuntimeException thrown by the callee context, but that is not the case of actual operation.
Most of the uncaught exceptions thrown by the callee will be propagated as [RevertedException](https://www.javadoc.io/static/foundation.icon/javaee-api/0.9.1/score/RevertedException.html).  See also [Context.call](https://www.javadoc.io/static/foundation.icon/javaee-api/0.9.1/score/Context.html#call(score.Address,java.lang.String,java.lang.Object...)). 
It's somewhat cumbersome to implement the same behaviors in tests module.

Note that javaee-unittest package is just for unit tests per methods, not for complex inter-call scenarios.  I think you need to use the integration tests module for negative intercall tests.

**Comment by AntonAndell** [comment]
@sink772 yeah Runtime Exception here is broad. What i wanna catch is if a Context.call raises a User Reverted exception. I see your point that this might be on the edge of what is supposed to be unit tested. But unit-testing smart contracts seem to be a little different. 

Take for example the scenario
```
        try {
            Context.call(Context.getAddress(), "doSomething", params);
        } catch (UserRevertException e) {
            handleHere();
        }
``` 
This can not be reproduced since the only exception raised is Assertion Error.  And we would then need to introduce static context mocking which is not very pretty and easy to get wrong. 

So what we could do then is throwing Reverted or User Reverted (both are Runtime Exceptions) which is probably why  solution works while being quite bad.  Could you explain the reasoning for throwing Assertion Error on invocation errors?

**Comment by sink772** [comment]
If you just want to catch the specific case (i.e. callee context was reverted by calling `Context.revert()`), yeah, we could add the exception handling only for that case.  However, what I want to emphasize here is we could not emulate the real cases exactly with the current unittest framework. It could be misleading if we couldn't emulate all the things.  This is why I recommend you to use the other integration test framework for the complex inter-call scenarios.

BTW, the code snippet above should be corrected as follows. Please do not confuse between `UserRevertException` vs `UserRevertedException`.
```
        try {
            Context.call(Context.getAddress(), "doSomething", params);
        } catch (UserRevertedException e) {
            handleHere();
        }
```

**Comment by AntonAndell** [comment]
Yeah thanks, i am aware of not being able to emulate a real case. My ambition is mostly to be able to write nice and readable unit tests for all functionality. 
To explain a bit more, what i am trying to test is a Voting function that tests the execution of vote actions. So verifying future execution. So basically a contact calling itself and reverting with UserRevertedException if successful. which could be neat to have working with the unitTesting framework. But i can agree it might be on the edge of what is unit Testing.  But there is not really a nice to test it otherwise. Either making it into a public function and mocking it or mocking the context class. 

But could be that this is such a niche case and if you don't see any other uses for it. I can agree we should skip it

**Comment by sink772** [comment]
@AntonAndell I've pushed a code for this issue.  Let me know if this is sufficient for your usage.

**Comment by sink772** [comment]
Good point. Thus I modified it not to throw UserRevertedException in outermost call frame, see d4243c9.
I think now it can be used for most of situations without breaking the existing test cases.

**Comment by AntonAndell** [comment]
Looks really good! Will try it out later
