### ISSUE TITLE
Change block time to use Unix Time

### ISSUE THREAD

**Issue by AntonAndell** [icon-project/javaee-unittest#23]
Not sure why System.nano() is used so might close the issue if there is a good reason.

In a production environment block timestamp is always UNIX formatted.

**Comment by mksong-icon** [comment]
You are right, so I have will fix it to use System.currentTimeMillis().
Thanks

**Comment by mksong-icon** [comment]
Fixed with two commits
https://github.com/icon-project/javaee-unittest/commit/000656f788697df086ebc4b5784d575c2dbc227a
https://github.com/icon-project/javaee-unittest/commit/c59c8a2e340855b2cb185408d4961e49f5064d12
