### ISSUE TITLE
Implicit int cast to BigInteger during interscore calls isn't supported

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/javaee-unittest#4]
In the current goloop version, a method with an `int` return type from a foreign SCORE is implicitely converted to `BigInteger` through an interscore call.

Related issue talking about this behavior : https://github.com/icon-project/goloop/issues/65

However, that behavior isn't implemented in javaee-unittest and make the tests fail with a ClassCastException: 

```java
this.decimals = ((BigInteger) Context.call(token_addr, "decimals")).intValue();
```

Such line fails to run because the "decimals" method from IRC2 returns an int natively. The unittest package uses the `int` return type instead of the `BigInteger` one.

How hard would it be to fix javaee-unittest in order to copy the goloop engine behavior ?

**Comment by sink772** [comment]
You might have noticed, I have modified the IRC2 javaee-tokens RI for `decimals` to have a return type of `BigInteger`.
https://github.com/sink772/javaee-tokens/commit/a4cad6c4c98a5307fd5a0b7e12e5e032cf64146e

This is just a workaround solution, but I believe you don't need to use `int` type here if you want to get the value via inter-call.
I think it's better to use `BigInterger` in all cases for external readonly methods.
