### ISSUE TITLE
Mocking VarDB values ?

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/javaee-unittest#8]
I'm trying to mock a VarDB value in a contract that is hard to modify at the intended value from method calls.

Let's say I have the following contract: 

```java
public class HelloWorld {
  private final VarDB<BigInteger> myVar = Context.newVarDB("myvar", BigInteger.class);
}
```

I managed to do that using the ServiceManager, by doing so : 

```java
public void mockMyVar (BigInteger value) {
    sm.pushFrame(owner, score.getAccount(), false, "setMyVar", ZERO);
    spy.myvar.set(value);
    sm.popFrame();
}
```

However, `pushFrame` and `popFrame` visibility are private by default.

Would it be acceptable to set these methods visibility to public ? 
Is there another way you can see to achieve what I want to do ?

Thanks!

**Comment by sink772** [comment]
Mockito framework is for that purpose. It seems you need to use Mockito, instead of modifying this project code.

**Comment by ICONationDevTeam** [comment]
I use Mockito, would you have an example code about how to modify a VarDB please ?

**Comment by sink772** [comment]
Well... it depends on your use cases. javaee-tokens project has some examples, but I'm not sure if it will be helpful to you.

**Comment by ICONationDevTeam** [comment]
I just need to mock a VarDB value to another during a single test. 
I can see there are verify/reset/ArgumentCaptor calls in javaee but nothing seems to match what I need to do

**Comment by sink772** [comment]
Mockito is a very versatile framework. I don't think you cannot do what you need with Mockito.
